var articulos = [
    { codigo: "A001", descripcion: "Agua embotellada (1L)", stock: 50, foto: "foto1.png", tipo: "agua", origen: ["donación", "gobierno"] },
    { codigo: "A002", descripcion: "Arroz (1kg)", stock: 30, foto: "foto2.png", tipo: "alimento", origen: [] },
    { codigo: "A003", descripcion: "Frijoles (1kg)", stock: 20, foto: "foto3.png", tipo: "alimento", origen: ["particular", "donación"] },
    { codigo: "A004", descripcion: "Leche en polvo (500g)", stock: 25, foto: "foto4.png", tipo: "alimento", origen: ["gobierno"] },
    { codigo: "A005", descripcion: "Pan de caja", stock: 40, foto: "foto5.png", tipo: "alimento", origen: ["empresa", "particular"] },
    { codigo: "A006", descripcion: "Enlatado de atún", stock: 60, foto: "foto6.png", tipo: "alimento", origen: [] },
    { codigo: "A007", descripcion: "Galletas saladas", stock: 35, foto: "foto7.png", tipo: "alimento", origen: ["gobierno", "empresa"] },
    { codigo: "A008", descripcion: "Manta térmica", stock: 15, foto: "foto8.png", tipo: "ropa", origen: ["particular"] },
    { codigo: "A009", descripcion: "Ropa de abrigo (varias tallas)", stock: 25, foto: "foto9.png", tipo: "ropa", origen: ["donación", "gobierno"] },
    { codigo: "A010", descripcion: "Calcetines de lana (par)", stock: 60, foto: "foto10.png", tipo: "ropa", origen: ["empresa"] },
    { codigo: "A011", descripcion: "Kit de primeros auxilios", stock: 20, foto: "foto11.png", tipo: "medicina", origen: ["donación"] },
    { codigo: "A012", descripcion: "Analgésicos (paracetamol, 500 mg)", stock: 100, foto: "foto12.png", tipo: "medicina", origen: ["gobierno"] },
    { codigo: "A013", descripcion: "Antiséptico (250 ml)", stock: 30, foto: "foto13.png", tipo: "medicina", origen: ["particular"] },
    { codigo: "A014", descripcion: "Vendajes elásticos", stock: 40, foto: "foto14.png", tipo: "medicina", origen: ["empresa", "donación"] },
    { codigo: "A015", descripcion: "Termómetro digital", stock: 15, foto: "foto15.png", tipo: "medicina", origen: ["gobierno"] },
    { codigo: "A016", descripcion: "Bolsas de dormir", stock: 10, foto: "foto16.png", tipo: "otros", origen: ["donación", "particular"] },
    { codigo: "A017", descripcion: "Colchón inflable", stock: 5, foto: "foto17.png", tipo: "otros", origen: ["empresa"] },
    { codigo: "A018", descripcion: "Linterna con pilas", stock: 20, foto: "foto18.png", tipo: "otros", origen: ["gobierno", "empresa"] },
    { codigo: "A019", descripcion: "Botella de agua purificada (5L)", stock: 10, foto: "foto19.png", tipo: "agua", origen: ["particular"] },
    { codigo: "A020", descripcion: "Sopa instantánea", stock: 45, foto: "foto20.png", tipo: "alimento", origen: ["donación"] },
    { codigo: "A021", descripcion: "Conserva de frutas", stock: 25, foto: "foto21.png", tipo: "alimento", origen: ["gobierno", "empresa"] },
    { codigo: "A022", descripcion: "Toallas higiénicas", stock: 40, foto: "foto22.png", tipo: "otros", origen: ["particular", "empresa"] },
    { codigo: "A023", descripcion: "Pañales para bebés (talla M)", stock: 35, foto: "foto23.png", tipo: "otros", origen: ["donación"] },
    { codigo: "A024", descripcion: "Jabón antibacteriano", stock: 60, foto: "foto24.png", tipo: "otros", origen: ["gobierno"] },
    { codigo: "A025", descripcion: "Pasta dental", stock: 50, foto: "foto25.png", tipo: "otros", origen: ["empresa", "particular"] },
    { codigo: "A026", descripcion: "Cepillos de dientes", stock: 75, foto: "foto26.png", tipo: "otros", origen: ["donación"] },
    { codigo: "A027", descripcion: "Champú", stock: 40, foto: "foto27.png", tipo: "otros", origen: ["gobierno"] },
    { codigo: "A028", descripcion: "Toallas de mano", stock: 30, foto: "foto28.png", tipo: "otros", origen: ["particular", "donación"] },
    { codigo: "A029", descripcion: "Desinfectante multiusos (1L)", stock: 20, foto: "foto29.png", tipo: "otros", origen: ["empresa"] },
    { codigo: "A030", descripcion: "Agua oxigenada (250ml)", stock: 20, foto: "foto30.png", tipo: "medicina", origen: ["gobierno", "empresa"] }
];
